# -*- coding: utf-8 -*-
"""brasil

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxZOfYgOCmaNNrcVmGf8TF-vzlpLhEaj
"""

import pandas as pd

df = pd.read_csv('/content/203966c5-6a14-4f27-ba2a-2aaa6fd55cda_Data.csv')

df

df = df.drop([1,2,3,4,5])
df = df.drop(['Series Name', 'Series Code', 'Country Name', 'Country Code'], axis=1)

df

df = df.T

df

divida = df.values.flatten().tolist()

divida

ano = []

for i in range(2010, 2024):
  if i <= 2024:
    ano.append(i)

ano

df_novo = pd.DataFrame({'Ano': ano, 'Divida': divida})

df_novo

df_novo = df_novo.set_index('Ano')

df_novo

import matplotlib.pyplot as plt
import seaborn as sns

df_novo.plot(kind='line', y='Divida', title='Evolução da Dívida Pública ao Longo dos Anos: Dívida x PIB', figsize=(10,4))
plt.xlabel('')  # Título do eixo X
plt.ylabel('Dívida em relacão ao PIB %')  # Título do eixo Y
plt.grid(True)  # Adicionando a grade ao gráfico
plt.savefig('evolucao_divida.png', dpi=300, bbox_inches='tight')
plt.show()