# -*- coding: utf-8 -*-
"""Desafios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mn42YDNmkgTmKf0s9H9qkx2I32CXcs15

# **Sobre o notebook**

Aproveite esse espaço para as atividades do curso de **Estatística com Python: resumindo e analisando dados** da Alura. Aqui você pode escrever e testar os códigos dos diversos exercícios do **Mão na Massa** envolvendo os aprendizados de cada aula.

Utilizando os conhecimentos adquiridos ao longo do curso, você precisará realizar uma **análise descritiva** básica de um conjunto de dados retirados da **Pesquisa Nacional por Amostra de Domicílios - 2015** do IBGE.

Nele, você irá avaliar os tipos dos dados e suas distribuições, calcular as medidas de tendência central, medidas separatrizes e de dispersão dos dados e construirá visuais como histogramas, boxplot, entre outras para responder às perguntas.

Este notebook foi construído com espaços para adicionar as células dos desafios propostos no curso, com eles você tem espaço para construir e executar suas soluções.

## **Dataset do Projeto**

O conjunto de dados que será explorado aqui é uma adaptação dos dados da **Pesquisa Nacional por Amostra de Domicílios - PNAD**. Ela investiga anualmente, de forma permanente, características gerais da população, de educação, trabalho, rendimento e habitação e outras, com periodicidade variável, de acordo com as necessidades de informação para o país, como as características sobre migração, fecundidade, nupcialidade, saúde, segurança alimentar, entre outros temas.

O levantamento dessas estatísticas constitui, ao longo dos 49 anos de realização da pesquisa, um importante instrumento para formulação, validação e avaliação de políticas orientadas para o desenvolvimento socioeconômico e a melhoria das condições de vida no Brasil.

### **Fonte dos Dados**

https://www.ibge.gov.br/estatisticas/sociais/populacao/9127-pesquisa-nacional-por-amostra-de-domicilios.html?edicao=9128

### **Variáveis do dataset**

> ### UF
> ***

Unidade federativa da pessoa responsável

> ### Sexo
> ***

Sexo biológico da pessoa responsável

<br>

|Código|Descrição|
|---|---|
|0|Masculino|
|1|Feminino|

> ### Idade
> ***

Idade da pessoa responsável na data de referência em anos.

> ### Cor
> ***

Cor ou raça da pessoa responsável com base na autodeclaração

<br>

|Código|Descrição|
|---|---|
|0|Indígena|
|2|Branca|
|4|Preta|
|6|Amarela|
|8|Parda|

> ### Anos de Estudo
> ***

Anos de estudo da pessoa responsável

<br>

|Código|Descrição|
|---|---|
|1|Sem instrução e menos de 1 ano|
|2|1 ano|
|3|2 anos|
|4|3 anos|
|5|4 anos|
|6|5 anos|
|7|6 anos|
|8|7 anos|
|9|8 anos|
|10|9 anos|
|11|10 anos|
|12|11 anos|
|13|12 anos|
|14|13 anos|
|15|14 anos|
|16|15 anos ou mais|
|17|Não determinados|

> ### Renda
> ***

Rendimento mensal do trabalho principal da pessoa responsável para 10 anos ou mais de idade.

> ### Altura (elaboração própria - dado sintético)
> ***

Altura da pessoa responsável em metros.

#### <font color='red'>Observação</font>
***
> Os seguintes tratamentos foram realizados nos dados originais:
> 1. Foram eliminados os registros onde a **Renda** era inválida (999 999 999 999);
> 2. Foram eliminados os registros onde a **Renda** era missing;
> 3. Foram considerados somente os registros das **Pessoas de Referência** de cada domicílio (responsável pelo domicílio).

## **Aula 01 - Entendendo os dados**

### **Mão na Massa - Explorando novos dados**

Você está treinando para ser uma pessoa cientista de dados e recebeu a demanda de investigar os dados da PNAD de 2015. A fim de testar as suas habilidades de análise de dados e os conceitos da estatística descritiva, responda às perguntas ao longo do notebook compartilhado.

#### **Importando os pacotes e configurando o ambiente**
"""

# Importando os pacotes do projeto
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""#### **Importe o dataset e armazene o conteúdo em um DataFrame**

**Dica:** Passe a url para a função que lê um arquivo do tipo `.csv`
"""

url = "https://raw.githubusercontent.com/alura-cursos/Estatisticas-Python-frequencias-medidas/refs/heads/main/dados/dados_desafio.csv"
dados = pd.read_csv(url)

"""#### **Visualize o conteúdo do DataFrame e leia as infos sobre os dados (linhas, colunas, tipos)**

**Dica:** Para observar as infos dos dados, utilize a função `info`
"""

dados.info()



"""#### **Explore brevemente a variável `UF` e investigue quantos dados possuímos para cada estado**

**Dica:** Para explorar, utilize as funções `unique`, `value_counts`, `reset_index` e `barplot`
"""

dados['UF'].unique()

dados_UF = dados[ 'UF'].value_counts()

dados_UF = dados_UF.reset_index()

plt.barh(dados_UF['UF'], dados_UF['count'])
plt.show()

"""#### **Transforme as variáveis `Sexo`, `Cor` e `Anos.de.Estudo` em Categorical e observe o resultado**

**Dica 1:** Para te auxiliar neste processo, a célula abaixo traz os vetores com os valores de cada coluna na ordem desejada.

**Dica 2:** Utilize a tabela no início do documento para fazer a relação dos valores atuais para os desejados.
"""

# Definindo as variáveis
sexo = {0: 'Masculino', 1: 'Feminino'}

cor = {0:'Indígena', 2:'Branca', 4:'Preta', 6:'Amarela', 8:'Parda'}

anos_de_estudo = {1:'Sem instrução e menos de 1 ano', 2:'1 ano', 3:'2 anos', 4:'3 anos', 5:'4 anos', 6:'5 anos',
    7:'6 anos', 8:'7 anos', 9:'8 anos', 10:'9 anos', 11:'10 anos', 12:'11 anos', 13:'12 anos',14:'13 anos',
    15:'14 anos', 16:'15 anos ou mais', 17:'Não determinados'
}



"""##### Sexo"""

dados[ 'Sexo_txt'] = pd.Categorical(
    dados['Sexo'],
    categories=[0, 1],
    ordered=True
)

dados['Sexo_txt'] = dados['Sexo_txt'].map(sexo)

dados



"""##### Cor"""

dados['Cor_txt'] = pd.Categorical(
    dados['Cor'],
    categories=[0, 2, 4, 6, 8],
    ordered=True
)

dados['Cor_txt'] = dados['Cor_txt'].map(cor)

"""##### Anos de Estudo"""

dados['Anos.de.Estudo.txt'] = pd.Categorical(
    dados['Anos.de.Estudo'],
    categories=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    ordered=True
)

dados['Anos.de.Estudo.txt'] = dados['Anos.de.Estudo.txt'].map(anos_de_estudo)



"""#### **Apresente em texto a menor e maior `Renda` da base de dados**

**Dica:** A renda é uma medida discreta. Utilizamos f-strings para formatar a string de forma mais legível e eficiente, substituindo diretamente as variáveis dentro da string
"""

print(f"A menor renda é o valor de R$ {min(dados['Renda']):.2f}, e a maior é o valor de R$ {max(dados['Renda']):,.2f}")

"""## **Aula 02 - Identificando o perfil do público**

### **Mão na Massa - Analisando o perfil das pessoas responsáveis**

Vamos prosseguir no treinamento, agora identificando o perfil das pessoas responsáveis pelo domicílio de acordo com os dados da PNAD de 2015. Responda às perguntas abaixo e reflita sobre os achados.

#### **Construa uma tabela de frequências das pessoas responsáveis pelo domicílio por `Cat.Sexo`. Adicione também uma coluna com esse valor em porcentagem.**
"""

res_por_sexo = (dados.groupby('Sexo_txt', observed=True).size().reset_index(name='Responsáveis'))

res_por_sexo['Responsáveis (%)'] = round(res_por_sexo['Responsáveis'] / res_por_sexo['Responsáveis'].sum() * 100, 1)
res_por_sexo



"""#### **Construa uma tabela de frequências absolutas e outra de relativas cruzando as variáveis `Cat.Sexo` e `Cat.Cor` das pessoas responsáveis pelo domicílio.**"""

freq_sexo_cor = pd.crosstab(dados['Sexo_txt'], dados['Cor_txt'])
freq_sexo_cor

freq_sexo_cor_porcent = round(freq_sexo_cor / freq_sexo_cor.sum() * 100, 1)
freq_sexo_cor_porcent



"""> #### Conclusões

Escreva suas conclusões aqui...

#### **Construa uma tabela cruzada para calcular a `Renda` média das pessoas responsáveis pelo domicílio em relação ao `Cat.Sexo` e `Cat.Cor`.**
"""

freq_sexo_cor = round(pd.crosstab(dados['Sexo_txt'], dados['Cor_txt'], values=dados['Renda'], aggfunc='mean'), 2)
freq_sexo_cor

"""> #### Conclusões

Escreva suas conclusões aqui...

## **Aula 03 - Analisando a tendência dos dados**

### **Mão na Massa - Analisando a renda das pessoas responsáveis**

Nesta etapa do treinamento, vamos analisar mais dados das pessoas responsáveis pelo domicílio de acordo com os dados da PNAD de 2015, focando na renda e na variável que criamos com as suas alturas. Responda às perguntas abaixo e reflita sobre os achados.

#### **Calcule as medidas de tendência central (média, mediana e moda) para a variável `Renda`**
"""

tendencia_central_renda = {
    'media': round(dados['Renda'].mean()),
    'mediana': round(dados['Renda'].median()),
    'moda': round(dados['Renda'].mode())
}

tendencia_central_renda







"""#### **Crie um gráfico de barras do Top 5 estados pela médias de `Renda`**

**Dica:** Para conseguir apresentar apenas os Top 5 estados utilize a função `head()` passando como variável quantos valores deseja apresentar.
"""

top_5_estados = (dados.groupby('UF', observed=True).agg(
      Renda = ('Renda', 'mean')
).reset_index())

top_5_estados['Renda'] = top_5_estados['Renda'].round(2)

top_5_estados = top_5_estados.head().sort_values(by='Renda', ascending=False)
top_5_estados





"""> #### Conclusões

Escreva suas conclusões aqui...

#### **Construa 3 tabelas cruzadas calculando a média, mediana e valores máximos de `Renda` relacionando as pessoas responsáveis por estado da Região Sudeste (`UF`) e por `Cat.Sexo`**
"""

regiao_sudeste = dados[dados['UF'].isin(['São Paulo', 'Minas Gerais', 'Rio de Janeiro', 'Espírito Santo'])]
regiao_sudeste

"""##### **Média**"""

media = round(pd.crosstab(regiao_sudeste['Sexo_txt'], regiao_sudeste['UF'], values=regiao_sudeste['Renda'], aggfunc='mean'))
media

"""##### **Mediana**"""

mediana = round(pd.crosstab(regiao_sudeste['Sexo_txt'], regiao_sudeste['UF'], values=regiao_sudeste['Renda'], aggfunc='median'))
mediana

"""##### **Renda Máxima**"""

renda_maxima = regiao_sudeste.groupby(['Sexo_txt', 'UF'])['Renda'].max().unstack()
renda_maxima

"""> #### Conclusões

Escreva suas conclusões aqui...

#### **Construa 2 histogramas com curva de densidade com os valores das colunas `Altura` e `Idade` de todas as pessoas responsáveis e compare as curvas obtidas com as suas  MTCs**

##### **Altura**
"""

plt.figure(figsize=(10,6))
sns.histplot(dados['Altura'], kde=True, bins=20)

plt.title('Curva de densidade da altura dos Responsáveis', fontsize=18)
plt.ylabel('')
plt.xlabel('Altura', fontsize=14)
plt.gca().tick_params(left=False)
plt.gca().set_yticklabels([])
sns.despine(left=True)

plt.savefig('curva_densidade.png')

plt.show()

dados_altura = {
    'media': round(dados['Altura'].mean(),1),
    'mediana': round(dados['Altura'].median(),1),
    'moda': round(dados['Altura'].mode(),1)
}
dados_altura

"""> #### Conclusões

Escreva suas conclusões aqui...

##### **Idade**
"""

media = dados['Idade'].mean()
mediana = dados['Idade'].median()
moda = dados['Idade'].mode()[0]

plt.figure(figsize=(10,6))
sns.histplot(data=dados['Idade'], bins=20, kde=True)

plt.axvline(media, color="red", linestyle="--", label=f'Média: {media:.2f}')
plt.axvline(mediana, color="green", linestyle="-.", label=f'Mediana: {mediana:.2f}')
plt.axvline(moda, color="black", linestyle=":", label=f'Moda: {moda:.2f}')
plt.title('Curva de densidade da idade dos responsáveis', fontsize=18, loc='left')
plt.xlabel('Idade', fontsize=14)
plt.ylabel('')
plt.tick_params(left=False)
plt.gca().set_yticklabels([])
sns.despine(left=True)

plt.legend()

plt.savefig('curva_densidade_altura.png')

plt.show()

dados_idade = {
    'media': round(dados['Idade'].mean()),
    'mediana': round(dados['Idade'].median()),
    'moda': round(dados['Idade'].mode())
}

dados_idade

"""> #### Conclusões

Escreva suas conclusões aqui...

## **Aula 04 - Investigando os dados dos colaboradores**

### **Mão na Massa - Analisando as rendas e suas divisões**

Nesta etapa do treinamento, vamos analisar os dados das pessoas responsáveis pelo domicílio de acordo com os dados da PNAD de 2015, por meio das medidas separatrizes. Responda às perguntas abaixo e reflita sobre os achados.

#### **Calcule o número de classes para `Renda` até R$15.000 utilizando a regra de Sturges**

$$k = 1 + \frac {10}{3}\log_{10}n$$

onde,

$k$ = número de classes

$n$ = número de observações.
"""











"""#### **Crie o histograma da `Renda` das pessoas responsáveis até R$15.000 seguindo o número de classes calculado anteriormente**

> **Observação:** Ao rodar o código para dividir os dados em faixas é possível que você observe o limite inferior da 1ª faixa com um valor negativo. Isto porque a *Regra de Sturges* define o intervalo mínimo da 1ª classe pela seguinte fórmula: $min(Renda) - (max(Renda) - min(Renda)) * 0.001$.
"""







"""> #### Conclusões

Escreva suas conclusões aqui...

#### **Responda as seguintes questões sobre o nosso dataset completo utilizando os conceitos que estudamos até aqui:**

##### **1. Qual o percentual de pessoas responsáveis que ganhava até um salário mínimo em 2015 (R$ 788,00)?**
"""



"""##### **2. Qual a renda máxima de 95% das pessoas responsáveis na pesquisa?**

"""



"""##### **3.   Qual a renda mínima dos 1% mais bem pagos da pesquisa?**"""



"""##### **4. Qual a renda máxima de 25%, 50% e 75% das pessoas responsáveis que receberam até R$ 6.000 de rendimento mensal? Construa o boxplot e traga o resumo desses dados.**

"""







"""> #### Conclusões

Escreva suas conclusões aqui...

#### **Construa o boxplot da `Renda` até o percentil 95% (`renda_6k`) das pessoas responsáveis por `Cat.Sexo` e `Cat.Cor`. Interprete o resultado.**

**Dica:** Para incluir uma 3ª variável na construção de um boxplot, utilize o parâmetro `hue` da seguinte maneira: `(x = Renda, y = Cat.Cor, hue = Cat.Sexo)`.
"""



"""#### **Qual a idade limite para 20% da população? Construa o histograma acumulado com curva de densidade, definindo a idade limite e quantas pessoas se encaixam nessa porcentagem.**

**Dica:** Para ler os últimos valores de um DataFrame utilize a função `tail()`.

Exemplo: `df.tail(3)` lê os ultimos 3 registros do DataFrame `df`.
"""















"""> #### Conclusões

Escreva suas conclusões aqui...

## **Aula 05 - Analisando a variação dos dados**

### **Mão na Massa - Analisando a variação da Renda das pessoas responsáveis**

Nesta última etapa do treinamento, vamos analisar os dados de renda das pessoas responsáveis pelo domicílio de acordo com os dados da PNAD de 2015, calculando a variação desta para determinadas características da amostra. Responda às perguntas abaixo e reflita sobre os achados.

#### **Responda as seguintes questões sobre o nosso dataset utilizando os conceitos que estudamos até aqui:**

##### **1.   Qual o desvio médio absoluto, a variância e desvio padrão da renda das pessoas responsáveis na pesquisa?**
"""



"""##### **2. Construa uma tabela com a média, mediana e desvio padrão para a renda das pessoas em relação aos Anos de Estudo. O que podemos interpretar com esses dados?**"""



"""> #### Conclusões

Escreva suas conclusões aqui...

##### **3.   Construa uma tabela com a média, mediana e desvio padrão para a renda das pessoas do sexo biológico masculino e feminino até R$ 15.000. O que podemos interpretar com esses dados?**
"""



"""> #### Conclusões

Escreva suas conclusões aqui...

#### **Construa um boxplot da `Renda` dos estados da Região Centro-Oeste até R$ 10.000 segundo o `Cat.Sexo`. Para interpretar o resultado construa 3 tabelas com cada uma das estatísticas descritivas (média, mediana e desvio padrão).**
"""





"""##### **Média**"""



"""##### **Mediana**"""



"""##### **Desvio Padrão**"""



"""> #### Conclusões

Escreva suas conclusões aqui...
"""