# -*- coding: utf-8 -*-
"""desmatamentoBrasil

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bP8scJjt36ESrnOvBDGjGWCiSaJglpwr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('desmatamento_prodes.csv')
df

df_desmantamento_ano = df[['referencia', 'area_total_desmatamento']]
df_desmantamento_ano

lula1 = [2003, 2004, 2005, 2006]
lula2 = [2007, 2008, 2009, 2010]
dilma1 = [2011, 2012, 2013, 2014]
dilma2 = [2015, 2016, 2017, 2018]
bolsonaro = [2019, 2020, 2021, 2022]

lula_1_desmatamento = df_desmantamento_ano[df_desmantamento_ano['referencia'].isin(lula1)]
lula_1_desmatamento_total = lula_1_desmatamento['area_total_desmatamento'].sum()
lula_1_desmatamento_total

lula2_desmatamento = df_desmantamento_ano[df_desmantamento_ano['referencia'].isin(lula2)]
lula_2_desmatamento_total = lula2_desmatamento['area_total_desmatamento'].sum()
lula_2_desmatamento_total

dilma1_desmatamento = df_desmantamento_ano[df_desmantamento_ano['referencia'].isin(dilma1)]
dilma1_desmatamento_total = dilma1_desmatamento['area_total_desmatamento'].sum()
dilma1_desmatamento_total

dilma2_desmatamento = df_desmantamento_ano[df_desmantamento_ano['referencia'].isin(dilma2)]
dilma2_desmatamento_total = dilma2_desmatamento['area_total_desmatamento'].sum()
dilma2_desmatamento_total

bolsonaro_desmatamento = df_desmantamento_ano[df_desmantamento_ano['referencia'].isin(bolsonaro)]
bolsonaro_desmatamento_total = bolsonaro_desmatamento['area_total_desmatamento'].sum()
bolsonaro_desmatamento_total

dados_desmatamento = {
    'Governo': ['Lula 1', 'Lula 2', 'Dilma 1', 'Dilma 2', 'Bolsonaro'],
    'Área Desmatada': [lula_1_desmatamento_total, lula_2_desmatamento_total, dilma1_desmatamento_total, dilma2_desmatamento_total, bolsonaro_desmatamento_total]
}

df_dados_desmatamento = pd.DataFrame(dados_desmatamento)
df_dados_desmatamento

cores = ['#b30225', '#b30225', '#b30225', '#b30225', '#0a016e']

def grafico_desmatamento():
  fig, ax = plt.subplots(figsize=(10,4))
  ax = sns.barplot(data=df_dados_desmatamento, x='Governo', y='Área Desmatada', palette=cores)
  ax.set_title('DESMATAMENTO DA FLORESTA AMAZÔNICA EM CADA GOVERNO \n 2002 a 2022', fontsize=15, pad=25)
  ax.set_xlabel('')
  ax.set_ylabel('')
  sns.despine(left=True, bottom=True)
  ax.set_yticklabels([])
  ax.tick_params(left=False, bottom=False)


  for i, Governo in enumerate(df_dados_desmatamento['Área Desmatada']):
      qtd = f' {Governo:,.0f} Km²'.replace(',','.')
      offset = 1.5e3
      ax.text(i, Governo + offset, qtd, fontsize = 12, ha = 'center', va = 'bottom')
  return ax

ax = grafico_desmatamento()
plt.savefig("desmatamento.png", dpi=300, bbox_inches="tight")
plt.show()

