# -*- coding: utf-8 -*-
"""imigracaoEX

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_nE-yaKM5wixwSpcb_S4ZPbHP39GYUX
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/canadian_immegration_data.csv')

df.set_index('Country', inplace=True)

df

america_do_sul = pd.DataFrame([df.loc['Brasil'], df.loc['Argentina'], df.loc['Peru'], df.loc['Colombia']])

america_do_sul

america_do_sul_ordenado = america_do_sul.sort_values(by='Total', ascending=False)

cores = ['#FFCD00', '#D91023', '#009440', '#75AADB']

fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(america_do_sul_ordenado.index, america_do_sul_ordenado['Total'], color=cores)
ax.set_title('Imigração de Colombia, Peru, Brasil e Argentina para o Canadá \nde 1980 a 2013', fontsize=18)
ax.set_ylabel('Número de imigrantes', fontsize=14)
ax.set_ylim(0, 90000)

for i, v in enumerate(america_do_sul_ordenado['Total']):
    ax.text(america_do_sul_ordenado.index[i], v + 2000, str(v),
            color='black', fontsize=10, ha='center')

fig.savefig('imigração_sul_canada.png', transparent=False, dpi=300, bbox_inches='tight')

plt.show()