# -*- coding: utf-8 -*-
"""Loja varejista

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SV4iq_Nhex9IeFMZ_86fi7rXSgotHZn
"""

import pandas as pd

lojas = ['A', 'B', 'C', 'D']

vendas_2022 = {'Jan': [100, 80, 150, 50],
    'Fev': [120, 90, 170, 60],
    'Mar': [150, 100, 200, 80],
    'Abr': [180, 110, 230, 90],
    'Mai': [220, 190, 350, 200],
    'Jun': [230, 150, 280, 120],
    'Jul': [250, 170, 300, 140],
    'Ago': [260, 180, 310, 150],
    'Set': [240, 160, 290, 130],
    'Out': [220, 140, 270, 110],
    'Nov': [400, 220, 350, 190],
    'Dez': [300, 350, 400, 250]
}

vendas = pd.DataFrame(vendas_2022)
vendas

vendas.index = lojas
vendas

import matplotlib.pyplot as plt

fig, axs = plt.subplots(2,2, figsize=(10,6))
fig.subplots_adjust(hspace=0.5, wspace=0.3)
fig.suptitle('Vendas 2022')

axs[0,0].plot(vendas.loc['A'])
axs[0,0].set_title('Loja A')


axs[0,1].plot(vendas.loc['B'])
axs[0,1].set_title('Loja B')

axs[1,0].plot(vendas.loc['C'])
axs[1,0].set_title('Loja C')

axs[1,1].plot(vendas.loc['D'])
axs[1,1].set_title('Loja D')

ymin = 0
ymax = 500

for ax in axs.ravel():
  ax.set_ylim(ymin, ymax)
  ax.grid(True)

for ax in axs.flat:
  ax.set_xlabel('Meses')
  ax.set_ylabel('Vendas')

plt.show()